keys:
  - &host_claw_box age15zj6e3qy9q3z7zf52w9lhe4plc7pvp2pzjw8kld8mcn48jwkkg3s4twxk6
  - &mgmt age1gspuhx8xu4w2wts5hxyrpqx5xs20chs84ty9gvvvw8xww4k62y7s77uteu

creation_rules:
  - path_regex: claw-box\.yaml$
    key_groups:
      - age:
          - *host_claw_box
          - *mgmt
